app:
  port: 8080
  ngrok: "https://3f9d-202-28-7-128.ngrok-free.app/"
  secret: "Hk89LSUPn3r4JDL@#@#$LJJKJDP00-.KJOS"
db:
  driver: "mysql"
  host: "127.0.0.1"
  port: 8889
  username: "root"
  password: "root"
  database: "meet_me"