// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "post": {
                "description": "Login user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "request body login",
                        "name": "users",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/interfaces.Login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.DataResponse"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Create user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Register user",
                "parameters": [
                    {
                        "description": "request body register",
                        "name": "users",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/interfaces.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.DataResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "return list users.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get all users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.DataResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "interfaces.Login": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "winner@mail.com"
                },
                "password": {
                    "type": "string",
                    "example": "winner"
                }
            }
        },
        "interfaces.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "firstname",
                "image",
                "password"
            ],
            "properties": {
                "birthday": {
                    "type": "string",
                    "example": "2023-08-12"
                },
                "email": {
                    "type": "string",
                    "example": "winner@mail.com"
                },
                "firstname": {
                    "type": "string",
                    "example": "Kanyapat"
                },
                "image": {
                    "type": "string"
                },
                "lastname": {
                    "type": "string",
                    "example": "Wittayamitkul"
                },
                "password": {
                    "type": "string",
                    "example": "winner"
                }
            }
        },
        "utils.DataResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "3f9d-202-28-7-128.ngrok-free.app",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Meet Me API",
	Description:      "This is a API for Meet Me.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
